Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Style/ExpandPathArguments:
  Enabled: false

Metrics/BlockLength:
  Max: 30

AllCops:
  Exclude:
    - config/**/*
    - Gemfile
    - Rakefile
    - bin/*
    - db/*
